language: node_js
node_js:
- '7'
sudo: false
os:
- linux
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
- "createdb travis_ci_test"
deploy:
  edge: true
  provider: cloudfoundry
  username:
    secure: tdG9/1XNKBhSA8Rf9qfu993l8tlPnPoVXlSG/CdZLiRsWSJK4wth2dM+/K+CH6IvrBicZgh1nR6iaoJ9PsPK3hYx1qmMmPQ+8/+hxEo+sCXF+hwDypmYStkfGQ7Ihp1aonT08aaW7UOxrqM15lQL6d3HOV2UY/24sCQFeYC5euo=
  password:
    secure: 2/4Cgn8Jt1OTLxJthuT/qEK8qXqCEThLqdKsuzM2S2heenDf+llNSz3WEhLUe8lMTYqg85s0hARlXn5bBgL+kR6SdITYzkb9GpsYKfntNhUZmncM5feR++AGrXl1IVGCL++qi8Lhn7hjCdtxDvcTELh/xr8UZKtXGg8YZmbRX8g=
  api: https://api.fr.cloud.gov
  organization: gsa-opp-analytics
  space: analytics-dev
  on:
    branch: master
